application: gosigner
version: 1
runtime: go
api_version: 1

handlers:
- url: /static
  static_dir: static
- url: /sign
  script: _go_app
- url: /
  static_files: html/index.html
  upload: html/(.*\.html)
- url: /about
  static_files: html/about.html
  upload: html/(.*\.html)
- url: /m
  static_files: html/m.html
  upload: html/(.*\.html)

  
